version: "3.5"

services:
  # If you wish to use a db other than mongo, this is 100% wrong
  db:
    image: postgres:latest
    restart: unless-stopped
    volumes:
      - heimdall_dbdata:/var/lib/postgresql/data
    expose:
      - "5432"
  web:
    build: .
    # image: web:1.0
    # image: mitre/heimdall:latest
    environment:
      DATABASE_URL: postgres://postgres@db/heimdall_postgres_production
      RAILS_SERVE_STATIC_FILES: "true"
      RAILS_ENV: production
      HEIMDALL_RELATIVE_URL_ROOT: ""
      DISABLE_SPRING: "true"
    env_file: .env-prod
    restart: unless-stopped
    command: /bin/sh -c "./bin/web"
    ports:
      - "3000:3000"
    depends_on:
      - "db"

volumes:
  heimdall_dbdata:
